### ISSUE TITLE
How to add npm/yarn ?

### ISSUE THREAD

**Issue by lchhieu** [dimadeush/docker-apache-php-symfony#24]

**Comment by dimadeush** [comment]
We are backend org and that's why we don't have frontend parts inside. Maybe you need to pay your attention to the repo https://github.com/systemsdk/node and add that docker container to your docker-compose.yml

**Comment by lchhieu** [comment]
I'm using api-platform and need run npm to can build admin component

**Comment by dimadeush** [comment]
We are not using api-platform but you can add docker container mentioned above and add inside everything that you need. Please follow steps inside README file.
