### ISSUE TITLE
php:8.2-apache image building but not starting

### ISSUE THREAD

**Issue by yasuke0x0** [dimadeush/docker-apache-php-symfony#26]
Environment

ProductName:            macOS
ProductVersion:         13.2.1
BuildVersion:           22D68
64-bit system

How to reproduce? 

make build && make start

What happens? 

All containers start except the php-apache (symfony) one. See logs in attachment.

How I solved it? 

I commented the line usermod -o -u $HOST_UID $USERNAME -d /home/$USERNAME \

Do you have any other solution? 

Attachments: 

![Capture d’écran 2023-09-14 à 11 15 22](https://github.com/systemsdk/docker-apache-php-symfony/assets/110788297/c1fb245e-4248-4231-bee4-1092b527bb24)
![Capture d’écran 2023-09-14 à 11 16 30](https://github.com/systemsdk/docker-apache-php-symfony/assets/110788297/d5770830-d715-41e0-bfff-281f1737dce0)

**Comment by dimadeush** [comment]
Hello
Can you, please, try to output next command on your Mac:
`$shell id -u`
Also please contact us via support email and we will try to help you.

**Comment by yasuke0x0** [comment]
`$shell id -u` gives `501`

**Comment by dimadeush** [comment]
We still didn't get response from you via support email. Unfortunately we don't have Mac and that's why it will be tricky. Please communicate with our support via support email and provide screen with error without commenting line, mentioned above (usermod -o -u ....).
Thanks.

**Comment by dimadeush** [comment]
closed due to no response
