### ISSUE TITLE
manifest unknown rabbitmq:management-alpine

### ISSUE THREAD

**Issue by oussaka** [dimadeush/docker-apache-php-symfony#27]
Hello

I have this error : 

> docker pull rabbitmq:3.13.7-management-alpine
> 3.13.7-management-alpine: Pulling from library/rabbitmq
> manifest for rabbitmq:3.13.7-management-alpine not found: manifest unknown: manifest unknown

so I moved on to another docker image in docker/rabbitmq/Dockerfile

> FROM masstransit/rabbitmq:4.0.2

**Comment by dimadeush** [comment]
Hello

Thanks for the report. Yes, as we can see there is something with the latest rabbitmq image 3.13.7 - https://github.com/docker-library/rabbitmq/issues/747.  You can use 3.13.6 until 3.13.7 will not be fixed.

**Comment by thaJeztah** [comment]
(I work at Docker and am currently in a call with the team) this looks to be the same cause as the ticket below (for another repository); the team is actively working on this;

- https://github.com/docker-library/docker/issues/519
- https://github.com/docker-library/docker/issues/520

https://www.dockerstatus.com also has been updated to reflect the current status

**Comment by thaJeztah** [comment]
Update on this issue; a colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"

There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images. These images will likely be processed later, which may be done after the weekend.

**Comment by dimadeush** [comment]
> Update on this issue; a colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"
> 
> There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images. These images will likely be processed later, which may be done after the weekend.

Hello Sebastiaan

Thanks for the update and for detail explanation. Now it's working.

**Comment by dimadeush** [comment]
fixed
