### ISSUE TITLE
security-checker no longer maintained

### ISSUE THREAD

**Issue by IronXtreme** [dimadeush/docker-apache-php-symfony#6]
Hi,

"make build" doesn't work anymore cause of the security-checker, i guess since January : [security-checker](https://github.com/sensiolabs/security-checker)

**Comment by dimadeush** [comment]
Hello
Yes, I know it but will fix it soon in this repo. Just need to transfer fix from here - https://github.com/dimadeush/docker-symfony-api/commit/2114a48f75e5a6ae736309c60b35eec661e08294.
Thanks

**Comment by dimadeush** [comment]
Done.
